# Generated by Django 5.2.1 on 2025-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_dados_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('linguagem', models.CharField(max_length=100)),
                ('visibilidade', models.CharField(choices=[('PU', 'Private'), ('PR', 'Public')], default='', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='dados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
