# Generated by Django 5.2.1 on 2025-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_repositorio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='visibilidade',
            field=models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='', max_length=2),
        ),
    ]
