# Generated by Django 5.2.1 on 2025-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_repositorio_visibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='visibilidade',
            field=models.CharField(choices=[('PU', 'Private'), ('PR', 'Public')], default='', max_length=2),
        ),
    ]
